Testing
YunoHost-Apps/hubzilla_ynh pull request #59
Opened 2020-12-17 18:52 UTC by anmol26s

## Problem
- *New Update available*

## Solution
- *Updated to version 5.0.5*

## PR Status
- [X] Code finished.
- [X] Tested with Package_check.
- [X] Fix or enhancement tested.
- [X] Upgrade from last version tested.
- [X] Can be reviewed and tested.

## Package_check results
---

2020-12-17 19:51 UTC, ericgaspar requested changes

2020-12-17 19:51 UTC, ericgaspar commented on README.md
> +[![Integration level](https://dash.yunohost.org/integration/hubzilla.svg)](https://dash.yunohost.org/appci/app/hubzilla) ![](https://ci-apps.yunohost.org/ci/badges/hubzilla.status.svg) ![](https://ci
```suggestion
[![Integration level](https://dash.yunohost.org/integration/hubzilla.svg)](https://dash.yunohost.org/appci/app/hubzilla) ![](https://ci-apps.yunohost.org/ci/badges/hubzilla.status.svg) ![](https://ci-apps.yunohost.org/ci/badges/hubzilla.maintain.svg)  
```
you need two spaces here to do a line break

2020-12-17 20:16 UTC, ericgaspar requested changes

2020-12-17 20:16 UTC, ericgaspar commented on README.md
>  [![Install Hubzilla with YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=hubzilla)
```suggestion
[![Install Hubzilla with YunoHost](https://install-app.yunohost.org/install-with-yunohost.svg)](https://install-app.yunohost.org/?app=hubzilla)
```
let's use the new svg badge!

2020-12-26 14:09 UTC, alexAubin approved these changes

2021-01-16 10:40 UTC, anmol26s commented
Outdated so closing this

2021-01-16 10:40 UTC, closed without merging